# Generated by Django 5.1.1 on 2024-09-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_icon_image',
            field=models.ImageField(upload_to='', verbose_name='画像'),
        ),
    ]
